// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nmxhoirjjeaetvuhjvqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5teGhvaXJqamVhZXR2dWhqdnFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYyNDM3MjQsImV4cCI6MjEwMTgxOTcyNH0.D1dIrZNOyk4ZR1D2wFxh45DRna0uw7lkHy-8UV_a74Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
